### ISSUE TITLE
getBonfTx todos

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/qsvaR#10]
* Similar ones to #9 
* Note that you expect to have a `tpm` assay at https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/R/getBonfTx.R#L10. So instead, you could add an argument called `assayname` or something like. See how they use `dimred` at https://github.com/Alanocallaghan/scater/blob/master/R/plotReducedDim.R#L90 which then at https://github.com/Alanocallaghan/scater/blob/master/R/plotReducedDim.R#L79 people have to specify the name of the assay ( in this case reducedDim) that they want to use. I'd recommend something like `assayname = "tpm"` such that the default is what you'd expect. You'll have to change `assays(covComb_tx)$tpm` to something that works with a object that contains the name, that is, something like https://github.com/LieberInstitute/recount3/blob/master/R/transform_counts.R#L82. You'll also want to check that the assayName exists, like at https://github.com/LieberInstitute/recount3/blob/master/R/transform_counts.R#L77. 
* Properly import `prcomp` https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/R/getBonfTx.R#L10. So add the `#' @importFrom package prcomp` syntax where `package` is the actual package where this function lives. Then use `usethis::use_package("package")` to edit the DESCRIPTION file #1. 
* I forget if we need to do the same with `log2()`, likely not. But if we do, we'll know thanks to #4.

**Comment by joshstolz** [comment]
updated documentation as recommended in the issues and added assayname option
