### ISSUE TITLE
Document how to use Salmon and SPEAQeasy output in the vignette

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/qsvaR#14]
Explore whether we can use the example data from `tximport` to create an RSE from `Salmon` transcript count output files and run the qSVA functions on it.

See:

* http://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html
* https://bioconductor.org/packages/release/workflows/vignettes/rnaseqDTU/inst/doc/rnaseqDTU.html#importing-counts-into-rbioconductor

@Nick-Eagles might be able to help compare the code from `tximport` and/or `rnaseqDTU` with what we have in `SPEAQeasy`.

You could also use the `SPEAQeasy-example` data (see https://github.com/LieberInstitute/SPEAQeasy-example/blob/master/pipeline_outputs/count_objects/rse_tx_Jlab_experiment_n42.Rdata) to document how to import those files and use them for this package.

**Comment by joshstolz** [comment]
we added flag to SPEAQeasy to subset to transcripts. Still needs to be added to the vignette.

https://github.com/LieberInstitute/SPEAQeasy/blob/fd150a49fe36ff2099c06fc7b93e5a30740bbe31/main.nf#L131
