### ISSUE TITLE
[BUG] Complete qSVA() wrapper

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/qsvaR#29]
It seems like a bug that `sig_transcripts` at https://github.com/LieberInstitute/qsvaR/blob/498143f803362e76dfca87ac81cee354a5c29416/R/qSVA.R#L23 is not used later on the `qSVA()` function.

**Comment by joshstolz** [comment]
https://github.com/LieberInstitute/qsvaR/blob/498143f803362e76dfca87ac81cee354a5c29416/R/qSVA.R#L24

This line should read:

DegTx <- getDegTx(rse_tx, type = sig_transcripts)

Though it may make more sense to change the variable to `type`

**Comment by lcolladotor** [comment]
Thanks for the hint Josh @joshstolz! We fixed this at https://github.com/LieberInstitute/qsvaR/commit/d9066dd9e34a338410e3c6080bd2b421a5f9ab6e and have added a unit test (see other commits for more details).
