### ISSUE TITLE
Update README files

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/qsvaR#7]
Once you have a main function you want to showcase, update the Example section at https://github.com/LieberInstitute/DeDHed/blob/main/README.Rmd#L42-L65. 

Once you have updated the main description of the package (the paragraph at #1), then you can update the goal at https://github.com/LieberInstitute/DeDHed/blob/main/README.Rmd#L23. 

To update the `README.md` file, use https://github.com/LieberInstitute/DeDHed/blob/main/dev/04_update.R#L29.

**Comment by joshstolz** [comment]
Readme file was udated and completed
