### ISSUE TITLE
Update citation

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/qsvaR#8]
Once you have a title for the package (from #1) and the updated authors list (also from #1), then update the CITATION file. See the `spatialLIBD` citation file as an example (https://github.com/LieberInstitute/spatialLIBD/blob/master/inst/CITATION).

https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/inst/CITATION

Note that you'll likely want to decide on the package name (#2) first since it'll likely be part of the title.

**Comment by joshstolz** [comment]
updated to include package name and authors. Will later need to update again when paper is out.
