### ISSUE TITLE
getDegTx todos

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/qsvaR#9]
* Document the `rse_tx` argument (parameter) at https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/R/getDegTx.R#L3. Since this takes as input a `RangedSummarizedExperiment` object, you'll likely want to use something like https://github.com/LieberInstitute/recount3/blob/master/R/create_rse_manual.R#L14 so you can link to the documentation of RSE objects.

<img width="1295" alt="Screen Shot 2021-11-02 at 11 27 14 AM" src="https://user-images.githubusercontent.com/2288213/139877613-3e5466b5-01c8-4d02-94ab-6016d9f13301.png">

See https://github.com/LieberInstitute/recount3/blob/master/R/create_rse_manual.R#L3-L6 for another example of how I use it in a sentence.

* Explain what the function returns at https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/R/getDegTx.R#L5. So that is, what is `covComb_tx` at https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/R/getDegTx.R#L11. Is it a matrix? data.frame? an RSE? What does it contain?

* Add a title at https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/R/getDegTx.R#L1. It cannot end with a period or #4 will throw an error. See https://github.com/LieberInstitute/recount3/blob/master/R/create_rse_manual.R#L1 for an example.

* Add a description paragraph like at https://github.com/LieberInstitute/recount3/blob/master/R/create_rse_manual.R#L2-L6 (starts with an empty line to differentiate it from the title). This one should end with a period, or you'll get an error at #2. Note that if you add a 3rd paragraph, it'll become the `details` section, like at https://github.com/LieberInstitute/recount3/blob/master/R/create_hub.R#L8-L11. 
 
* Make sure that we tell R to import `SummarizedExperiment`. Since users will interact a lot with RSE objects, you might want to `depend` instead of `import` the `SummarizedExperiment` package. So that involves editing #1 with https://github.com/LieberInstitute/recount3/blob/master/DESCRIPTION#L36-L37 which you can do with `usethis::use_package("SummarizedExperiment", "depends")` (or something like that). If you'd prefer to `import`, then you can use some examples from https://github.com/LieberInstitute/recount3/blob/master/R/create_rse_manual.R#L17-L23. For https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/R/getDegTx.R#L10, that would be `#' @importFrom SummarizedExperiment "["`

* Currently your function uses `sig_transcripts` which is not specified by the user. Is that an object that lives inside the package? That is, data contained in the package? If we are choosing between multiple models, you might want to make a helper function that chooses between a few models. See https://github.com/LieberInstitute/recount3/blob/master/R/annotation_options.R for an example. Note the use of the `match.arg()` function at https://github.com/LieberInstitute/recount3/blob/master/R/annotation_options.R#L17 which helps give useful errors to users if the input is not among the allowed options at https://github.com/LieberInstitute/recount3/blob/master/R/annotation_options.R#L16. See how I use `annotation_options()` in other functions like at https://github.com/LieberInstitute/recount3/blob/master/R/create_rse_manual.R#L120 

* Add examples to showcase how this function is used. So add code below https://github.com/LieberInstitute/DeDHed/blob/53103928435e2fdade736de338d52bb08cc3ec36/R/getDegTx.R#L8. Like https://github.com/LieberInstitute/recount3/blob/master/R/annotation_options.R#L13-L15 or https://github.com/LieberInstitute/recount3/blob/master/R/create_rse_manual.R#L30-L112

**Comment by joshstolz** [comment]
updated function documentation to include all above suggestions.
